name: format-action
inputs:
  template:
    description: "format template"
    required: true
  variable:
    description: "variable to render with format template"
    required: true
  ai:
    description: "variable"
    required: false
  need-escape-chars:
    description: 'char sequence that need escape'
    required: false
    default: ''
  escape-char:
    description: 'escape-char'
    required: false
    default: '_'
outputs:
  result:
    description: 'format result'
#    value: ${{ steps.final-output.outputs.result }}
runs:
  using: node20
  main: index.mjs
