name: gemini-STT
inputs:
  bvid:
    description: "Bilibili bvid"
    required: true
  token:
    description: "gemini-token"
    required: true
  bili-proxy:
    description: "bili-proxy-host"
    required: true
  system-prompt:
    description: "system-prompt"
    required: true
  prompt:
    description: "prompt"
    required: true
  model:
    description: "gemini model"
    required: true
outputs:
  markdown:
    description: markdown
    value: ${{ steps.final-output.outputs.markdown }}
runs:
  using: "composite"
  steps:
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    - name: get and download video
      id: bili
      uses: ktKongTong/bili-action@v0.2.10
      with:
        bvid: ${{ inputs.bvid }}
        proxy-stream-host: ${{ inputs.bili-proxy }}
        audio: true
        audio-file-template: "output/{bvid}.mp4"
    - name: convert to mp3
      shell: bash
      run: ffmpeg -i output/${{ steps.bili.outputs.bvid }}.mp4 -ar 16000 output/${{ steps.bili.outputs.bvid }}.mp3
    - name: Upload output.mp3
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.bili.outputs.bvid }}.mp3
        path: output/${{ steps.bili.outputs.bvid }}.mp3
        if-no-files-found: error
        retention-days: 1
    - name: speech to text with gemini
      uses: ktKongTong/gemini-action@v0.2.1
      id: gemini-stt
      with:
        token: ${{inputs.token}}
        model: ${{inputs.model}}
        file-path: output/${{ steps.bili.outputs.bvid }}.mp3
        prompt: ${{ inputs.prompt }}
        system-prompt: ${{ inputs.system-prompt }}
        file-mime: audio/mp3
    - name: show result
      shell: bash
      run: |
        echo "${{steps.gemini-stt.outputs.output}}" > output.md
        cat output.md
    - name: createHead
      shell: bash
      run: |
        echo '---
        title: ${{ steps.bili.outputs.title }}
        description: ${{steps.bili.outputs.desc }}
        tag: []
        date: ${{steps.bili.outputs.pubdate }}
        bvid: ${{steps.bili.outputs.bvid }}
        ---
        ' >> tmp.md
        cat output.md >> tmp.md
    - name: set output
      id: final-output
      shell: bash
      run: |
        echo 'markdown<<EOF' >> $GITHUB_OUTPUT
        cat tmp.md >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    - name: clean file
      shell: bash
      run: |
        rm -f video.json
        rm -f tmp.md
        rm -f output.md
        rm -rf output

#    - name: Upload output.md
#      uses: actions/upload-artifact@v4
#      with:
#        name: tmp.md
#        path: tmp.md
#        if-no-files-found: error
#        retention-days: 1
