name: bili-batch
on:
  workflow_dispatch:
    inputs:
      mid:
        required: true
        description: "Bilibili member id"
      keywords:
        required: true
        description: "keywords filter"
      prompt:
        description: "prompt"
        default: |
          下面是一段音频，请识别为文本。不要返回额外的内容。
          拆分为合适的段落，并适当的加上标点符号标记。
          段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
          请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
          此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。
        required: false
      model:
        description: "gemini model"
        type: choice
        default: "gemini-2.0-flash"
        options:
          - "gemini-2.0-pro-exp-02-05"
          - "gemini-2.0-flash"

env:
  mid: ${{ github.event.inputs.mid }}
  keywords: ${{ github.event.inputs.keywords }}
  prompt: ${{ github.event.inputs.prompt || '下面是一段音频，请识别为文本。不要返回额外的内容。拆分为合适的段落，并适当的加上标点符号标记。段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。' }}
  model: ${{ github.event.inputs.model || 'gemini-2.0-pro-exp-02-05' }}
jobs:
  batch-get-video:
    runs-on: ubuntu-latest
    outputs:
      videos: ${{ steps.bili.outputs.result }}
    steps:
      - name: get and download video
        id: bili
        uses: ktKongTong/bili-action@v0.2.6
        with:
          mid: ${{ env.mid }}
          keyword: ${{ env.keywords }}
          batch: true
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: | 
            const videos = JSON.parse(${{ toJSON(steps.bili.outputs.batch) }})
            const chunk1 = videos.slice(0, 255)
            // .map(it=>it.bvid)
            console.log(chunk1)
            return chunk1
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

  get-video-item:
    needs: [batch-get-video]
    runs-on: ubuntu-latest
    strategy:
      matrix: # maximum of 256 configurations
        bvid: ${{ fromJSON(needs.batch-get-video.outputs.videos).*.bvid }}
    steps:
      - name: show result
        run: |
          echo "current bvid ${{ matrix.bvid }}"