name: bili-batch
on:
  workflow_dispatch:
    inputs:
      mid:
        required: true
        description: "Bilibili member id"
      keywords:
        required: true
        description: "keywords filter"
      prompt:
        description: "prompt"
        default: |
          下面是一段音频，请识别为文本。不要返回额外的内容。
          拆分为合适的段落，并适当的加上标点符号标记。
          段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
          请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
          此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。
        required: false
      model:
        description: "gemini model"
        type: choice
        default: "gemini-2.0-flash"
        options:
          - "gemini-2.0-pro-exp-02-05"
          - "gemini-2.0-flash"

env:
  mid: ${{ github.event.inputs.mid }}
  keywords: ${{ github.event.inputs.keywords }}
  prompt: ${{ github.event.inputs.prompt || '下面是一段音频，请识别为文本。不要返回额外的内容。拆分为合适的段落，并适当的加上标点符号标记。段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。' }}
  model: ${{ github.event.inputs.model || 'gemini-2.0-pro-exp-02-05' }}
jobs:
  batch-get-video:
    runs-on: ubuntu-latest
    outputs:
      videos: ${{ steps.set-result.outputs.result }}
    steps:
      - name: get and download video
        id: bili
        uses: ktKongTong/bili-action@v0.2.6
        with:
          mid: ${{ env.mid }}
          keyword: ${{ env.keywords }}
          batch: true
      - name: show result
        run: echo "${{join(fromJSON(steps.bili.outputs.batch).*.bvid)}}"
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: | 
            const bvids = "${{ join(fromJSON(steps.bili.outputs.batch).*.bvid) }}"
            const chunk1 = bvids.split(',').slice(0,10)
            // .map(it=>it.bvid)
            console.log(chunk1)
            return chunk1
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: 'batch/${{env.mid}}/${{env.keywords}}'
  get-video-item:
    needs: [batch-get-video]
    runs-on: ubuntu-latest
    strategy:
      matrix: # maximum of 256 configurations
        bvid: ${{ fromJSON(needs.batch-get-video.outputs.videos) }}
    steps:
      - name: show result
        run: |
          echo "current bvid ${{ matrix.bvid }}"
      - uses: actions/checkout@v4
        with:
          ref: 'batch/${{env.mid}}/${{env.keywords}}'
          token: '${{ secrets.PAT }}'
      - name: get and download video
        id: bili
        uses: ktKongTong/bili-action@v0.2.6
        with:
          bvid: ${{ matrix.bvid }}
      - id: path-resolver
        uses: ktKongTong/simple-format-action@v0.1.0
        with:
          data: ${{ steps.bili.outputs.video }}
          rule-file: .github/format.rule.yml
          fallback-template: |
            filename:{{pubdate}}-{{title}}.md
            filepath:docs/{{owner.name}}
      - id: call-stt-workflow
        uses: ./.github/actions/gemini-stt
        with:
          bvid: ${{ steps.bili.outputs.bvid }}
          token: ${{ secrets.GEMINI_TOKEN }}
          bili-proxy: ${{ secrets.BILI_STREAM_PROXY }}
          prompt: ${{ env.prompt }}
          model: ${{ env.model }}
      - name: move to dest
        run: |
          filepath="${{steps.path-resolver.outputs.filepath}}"
          filename="${{steps.path-resolver.outputs.filename}}"
          echo "$filepath"
          echo "$filename"
          mkdir -p $filepath
          echo "${{ steps.call-stt-workflow.outputs.markdown }}" > $filepath/$filename
          ls -l $filepath
      - name: commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "${{ github.actor }}"
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: ":memo: new docs ${{ steps.bili.outputs.title }}"
          add: 'docs/**/*.md'
