name: bili-stt
on:
  workflow_dispatch:
    inputs:
      bvid:
        description: 'Bilibili bvid'
      prompt:
        description: 'prompt'
        default: |
          下面是一段音频，请识别为文本。不要返回额外的内容。
          拆分为合适的段落，并适当的加上标点符号标记。
          段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
          请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
          此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。
        required: false
      model:
        description: 'gemini model'
        type: choice
        default: "gemini-2.0-pro-exp-02-05"
        options:
          - 'gemini-2.0-pro-exp-02-05'
          - 'gemini-2.0-flash'

jobs:
  get-video:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: get and download video
      id: bili
      uses: ktKongTong/bili-action@v0.2.4
      with:
        bvid: ${{ inputs.bvid }}
    - id: call-stt-workflow
      uses: ./.github/actions/gemini-stt
      with:
        bvid: ${{ inputs.bvid }}
        token: ${{ secrets.GEMINI_TOKEN }}
        bili-proxy: ${{ secrets.BILI_STREAM_PROXY }}
    - name: move to dest
      run: |
        echo '${{ toJSON(steps.call-stt-workflow.outputs) }}'
        filepath=docs/${{ fromJSON(steps.bili.outputs.owner).name }}/${{ steps.bili.outputs.pubdate }}-${{ steps.bili.outputs.title }}.md
        mkdir -p docs/${{ fromJSON(steps.bili.outputs.owner).name }}
        echo "${{ steps.call-stt-workflow.outputs.markdown }}" > tmp.md
        mv tmp.md $filepath
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: ":memo: new docs ${{ steps.bili.outputs.title }}"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        delete-branch: true
        branch: fetch/${{ steps.bili.outputs.bvid }}
        title: ":memo: new docs ${{ steps.bili.outputs.title }}"
        add-paths: |
          docs/**/*.md
          images/**/*.webp
        base: master
        body: |
          ":memo: new docs ${{ steps.bili.outputs.title }}"
          - Auto-generated by action: [create-pull-request](https://github.com/peter-evans/create-pull-request) with dify
        labels: |
          automated pr
        draft: false