name: bili-stt
on:
  workflow_dispatch:
    inputs:
      bvid:
        description: "Bilibili bvid"
      prompt:
        description: "prompt"
        default: |
          请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
          此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。
        required: false
        type: string
      system-prompt:
        description: "system-prompt"
        default: |
          下面是一段音频，请识别为文本。不要返回额外的内容。
          拆分为合适的段落，并适当的加上标点符号标记。
          段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
        required: false
        type: string
      model:
        description: "gemini model"
        type: choice
        default: "gemini-2.0-pro-exp-02-05"
        options:
          - "gemini-2.0-pro-exp-02-05"
          - "gemini-2.0-flash"
  workflow_call:
    inputs:
      bvid:
        description: "Bilibili bvid"
        required: true
        type: string
      prompt:
        description: "prompt"
        default: |
          请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
          此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。
        required: false
        type: string
      system-prompt:
        description: "system-prompt"
        default: |
          下面是一段音频，请识别为文本。不要返回额外的内容。
          拆分为合适的段落，并适当的加上标点符号标记。
          段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
        required: false
        type: string
      model:
        type: string
        description: "gemini model"
        default: "gemini-2.0-pro-exp-02-05"
        required: true
env:
  bvid: ${{ github.event.inputs.bvid }}
  prompt: ${{ github.event.inputs.prompt || '下面是一段音频，请识别为文本。不要返回额外的内容。拆分为合适的段落，并适当的加上标点符号标记。段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 `@@@` 进行标识。' }}
  model: ${{ github.event.inputs.model || 'gemini-2.0-pro-exp-02-05' }}
jobs:
  get-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get and download video
        id: bili
        uses: ktKongTong/bili-action@v0.2.8
        with:
          bvid: ${{ env.bvid }}
      - id: path-resolver
        uses: ktKongTong/simple-format-action@v0.1.0
        with:
          data: ${{ steps.bili.outputs.video }}
          rule-file: .github/format.rule.yml
          fallback-template: |
            filename:{{pubdate}}-{{title}}.md
            filepath:docs/{{owner.name}}
      - id: call-stt-workflow
        uses: ./.github/actions/gemini-stt
        with:
          bvid: ${{ steps.bili.outputs.bvid }}
          token: ${{ secrets.GEMINI_TOKEN }}
          bili-proxy: ${{ secrets.BILI_STREAM_PROXY }}
          prompt: ${{ env.prompt }}
          system-prompt: ${{ inputs.system-prompt }}
          model: ${{ env.model }}
      - name: move to dest
        run: |
          filepath="${{steps.path-resolver.outputs.filepath}}"
          filename="${{steps.path-resolver.outputs.filename}}"
          echo "$filepath"
          echo "$filename"
          mkdir -p $filepath
          echo "${{ steps.call-stt-workflow.outputs.markdown }}" > $filepath/$filename
          ls -l $filepath
          git add $filepath
      # create pr or commit directly
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: ":memo: new docs ${{ steps.bili.outputs.title }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          branch: fetch/${{ steps.bili.outputs.bvid }}
          title: ":memo: new docs ${{ steps.bili.outputs.title }}"
          add-paths: |
            docs/**/*.md
            images/**/*.webp
          base: main
          body: |
            ":memo: new docs ${{ steps.bili.outputs.title }}"
            - Auto-generated by action: [create-pull-request](https://github.com/peter-evans/create-pull-request) with dify
          labels: |
            automated pr
          draft: false
