name: bili-v2
on:
  workflow_call:
    inputs:
      bvid:
        description: "Bilibili bvid"
        required: true
        type: string
      filepath-template:
        description: "filepath-template"
        required: false
        type: string
      system-prompt-template:
        description: "system-prompt-template"
        required: false
        type: string
      prompt-template:
        description: "prompt"
        required: false
        type: string
      markdown-template:
        description: "markdown-template"
        required: false
        type: string
      exec-even-exist:
        type: 'boolean'
        required: false
      model:
        type: string
        description: "gemini model"
        default: "gemini-2.0-flash"
  workflow_dispatch:
    inputs:
      bvid:
        description: "Bilibili bvid"
        required: true
        type: string
      filepath-template:
        description: "filepath-template"
        required: false
        type: string
      system-prompt-template:
        description: "system-prompt-template"
        required: false
        type: string
      prompt-template:
        description: "prompt-template"
        required: false
        type: string
      markdown-template:
        description: "markdown-template"
        required: false
        type: string
      exec-even-exist:
        type: 'boolean'
        required: false
        default: 'false'
      model:
        description: "gemini model"
        type: choice
        default: "gemini-2.0-flash"
        options:
          - "gemini-2.0-pro-exp-02-05"
          - "gemini-2.0-flash"

env:
  bvid: ${{github.event.inputs.bvid }}
  exec-even-exist: ${{ github.event.inputs.exec-even-exist }}
  filepath-template: ${{ github.event.inputs.filepath-template }}
  prompt-template: ${{ github.event.inputs.prompt-template }}
  system-prompt-template: ${{ github.event.inputs.system-prompt-template }}
  markdown-template: ${{ github.event.inputs.markdown-template }}
  commit-message-template: ${{ github.event.inputs.commit-message-template }}
  model: ${{ github.event.inputs.model }}

  branch: 'fetch/${{inputs.bvid}}'
jobs:
  get-video:
    runs-on: ubuntu-latest
    steps:
      - name: get videos
        id: bili
        uses: ktKongTong/bili-action@v0.2.10
        with:
          bvid: ${{ env.bvid }}
      - uses: actions/checkout@v4
      - name: get content
        uses: ./.github/actions/bili-fetch-v2
        with:
          token: ${{ secrets.GEMINI_TOKEN }}
          github-token: ${{ secrets.PAT }}
          model: ${{ env.model }}
          bvid: ${{ env.bvid }}
          bili-proxy: ${{ secrets.BILI_STREAM_PROXY }}
          exec-even-exist: ${{ env.exec-even-exist }}
          branch: ${{ env.branch }}
          type: 'pr'
          filepath-template: ${{ env.filepath-template }}
          markdown-template: ${{ env.markdown-template }}
          prompt-template: ${{ env.prompt-template }}
          system-prompt-template: ${{ env.system-prompt-template }}
          commit-message-template: ":memo: new docs ${{ steps.bili.outputs.title }}"
